<?php include 'include/index_header.php';?>

<?php

if (!isset($_SESSION['user_id'])) {
    header("location:".BASE_PATH.'logout');
    exit;
}
$user_session = $_SESSION['user_session'];

$tfacode = $_SESSION['tfa'];
$secret = $_SESSION['key'];

require_once 'googleLib/GoogleAuthenticator.php';

$ga = new GoogleAuthenticator();

$qrCodeUrl = $ga->getQRCodeGoogleUrl($user_session, $secret);

if (isset($_POST['code'])) {
    $code=$_POST['code'];
    $secret = $_SESSION['key'];


    $checkResult = $ga->verifyCode($secret, $code, 2);    // 2 = 2*30sec clock tolerance

    if ($checkResult) {

        header("Location:".BASE_PATH.'myaccount');
    } else {
        $failcode = "Failed Code Incorrect";
    }
}
ob_end_flush();

?>
<!DOCTYPE html>
<html>

<body>


<div class="content">

    <link href="css/usercenter.css" rel="stylesheet" type="text/css">


<div class="main_content  acc-m-con">
       <div class="m_title"><h4 align="center">Enter the verification code generated by Google Authenticator app on your phone.</h4></div>


            <div align="center" class="sectioncont">
<form enctype="application/x-www-form-urlencoded" method="post" action="">

                <table>

<label><h4>Enter Google Authenticator Code</label><h4><br>
<input type="text" name="code" /><br><br><br>
<input type="submit" class="sub-btn"/><br>
<div style="width:50%;" id="alertmsg1"></div>
</form>
<p class="text-center" style="color:red;"> <?php if (isset($failcode)) {
    echo $failcode;
}?> </p>
</table>
</form>
</div>

</div>
</div>

<?php include 'include/footer.php';?>
</body>
</html>
<style>
.main_content
{
    width:100% !important;
}
</style>
<script>
$("a").click(function(){

document.getElementById('alertmsg1').innerHTML='<div class="alert alert-danger"><strong>Please Verifyed first !!!</strong>  </div>';

return false;

});
</script>
